### PR TITLE
fix a nil pointer error bug

### PR DESCRIPTION
**Pull request by Bjohnson131**
### Issue dell/csi-baremetal#

fixes a bug where the operator crashes if certain args aren't passed into the controller.

## PR checklist
- [ ] Add link to the issue
- [ ] Choose Project
- [ ] Choose PR label
- [ ] New unit tests added
- [ ] Modified code has meaningful comments
- [ ] All TODOs are linked with the issues
- [ ] All comments are resolved

## Testing
_Testing details_

### CODE REVIEW

**Review by SarahAFochs — APPROVED** [review]

**Review by vgupta-mickey — APPROVED** [review]

**Comment by Bjohnson131** [comment]
I've created an image to validate with- https://hub.docker.com/repository/docker/bjohnson131/csibm-operator-fork 
tag: [1.1.0-110.13f8716](https://hub.docker.com/layers/bjohnson131/csibm-operator-fork/1.1.0-110.13f8716/images/sha256-6bfe085d22c7caca11f94e996a5b4df8cad2e2a1f0d254d9c86102da40fc2bf2?context=repo) 

after switching the image, my  csi-baremetal-controller deployment gets the default values:


```yaml
      - args:
        - --csi-address=$(ADDRESS)
        - --extra-create-metadata
        - --feature-gates=Topology=true
        - --timeout=10s
        - --retry-interval-start=1s
        - --retry-interval-max=5m
        - --worker-threads=2
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: objectscale/csi-provisioner:v3.1.0
        imagePullPolicy: Always
        name: csi-provisioner
        resources: {}
        terminationMessagePath: /var/log/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: csi-socket-dir
        - mountPath: /crash-dump
          name: crash-dump
```

**Comment by Bjohnson131** [comment]
Ping: @yimingwangdell  @libzhang @CraneShiEMC @yanxiucai @aiqiEMC 
Could this be merged, please?

**Comment by yimingwangdell** [comment]
@Bjohnson131 this value comes from charts/csi-baremetal-deployment/values.yaml, I don't see why it could be a nil.

**Comment by Bjohnson131** [comment]
> @Bjohnson131 this value comes from charts/csi-baremetal-deployment/values.yaml, I don't see why it could be a nil. also please open an issue before commit PR, see https://github.com/dell/csi-baremetal/blob/master/docs/CONTRIBUTING.md, otherwise we may not notice the PR.

Hello, In this case, provisioner.Args could 100% be nil, given that none have been set at the time of deployment.
the values themselves will never be nil, but the underlying Args variable can be of value nil if there are no arguments set here: https://github.com/dell/csi-baremetal-operator/blob/master/charts/csi-baremetal-deployment/templates/csi-baremetal_v1_deployment.yaml#L52

**Comment by yimingwangdell** [comment]
@Bjohnson131 could you paste the way you install csi-operator?

 if you deploy it with helm package(helm install csi-operator **helm package .tgz file** --set image.tag=**tag** -- set global.registry=**helm registry address**)

the Args will be fetched from https://github.com/dell/csi-baremetal-operator/blob/598c0e4d39d3680e2c15e9e39dc0b42e9c4aee44/charts/csi-baremetal-deployment/values.yaml#L95 

 no additional configurations are needed.

**Comment by Bjohnson131** [comment]
> @Bjohnson131 could you paste the way you install csi-operator?

sadly, I cannot- This was over a year ago, and the helm install is no longer present on my cluster.

It was likely very similar to the "vanilla kubernetes" install on the readme.

**Comment by yimingwangdell** [comment]
@Bjohnson131 if that, I prefer to close this PR, because we are using csi in our product every day, Args should be existing.

**Comment by Bjohnson131** [comment]
> @Bjohnson131 if that, I prefer to close this PR, because we are using csi in our product every day, Args should be existing.

can defaults be hard-coded, then?  It's an awfully frustrating thing to see that a program doesn't work without certain arguments (and additionally that it gives you a nil pointer error instead of any sort of warning that you're missing arguments)..

**Pull request closed without merging**
